name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
      - release
  pull_request:
    branches:
      - main
      - dev
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter with specific version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Set the specific version of Flutter

      # Cache Flutter dependencies (optional, speeds up builds)
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
            build/
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies (flutter pub get)
      - name: Install dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test

      # Build the app (optional, you can add other build types like iOS or web)
      - name: Build APK (release)
        run: flutter build apk --release
